name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  BACKEND_IMAGE: ${{ secrets.DOCKER_USER }}/backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USER }}/frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # 2️⃣ Setup Java
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️⃣ Build Backend
    - name: Build Backend
      run: |
        cd Application/backend
        mvn clean install -DskipTests

    # 4️⃣ SonarQube (FIXED - Maven way)
    - name: SonarQube Scan
      run: |
       cd Application/backend
       mvn sonar:sonar \
          -Dsonar.projectKey=turkardiksha345-oss_DevOps-GitOps-Project \
          -Dsonar.organization=turkardiksha345-oss \
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}


    # 5️⃣ Snyk (SCA)
    - name: Install Snyk
      run: npm install -g snyk

    - name: Snyk Auth
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Test
      run: |
        cd Application/backend
        snyk test || true

    # 6️⃣ Build Docker Images
    - name: Build Backend Image
      run: docker build -t $BACKEND_IMAGE:${{ github.sha }} Application/backend

    - name: Build Frontend Image
      run: docker build -t $FRONTEND_IMAGE:${{ github.sha }} Application/frontend

    # 7️⃣ Trivy Scan (FIXED)
    - name: Scan Backend Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        severity: CRITICAL,HIGH
        exit-code: 1

    - name: Scan Frontend Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
        severity: CRITICAL,HIGH
        exit-code: 1

    # 8️⃣ Docker Login
    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    # 9️⃣ Push Images
    - name: Push Backend Image
      run: docker push $BACKEND_IMAGE:${{ github.sha }}

    - name: Push Frontend Image
      run: docker push $FRONTEND_IMAGE:${{ github.sha }}

    # 🔟 Update Manifest Repo
    - name: Update Manifest Repo
      run: |
        git clone https://${{ secrets.GIT_TOKEN }}@github.com/YOUR_USERNAME/manifest-repo.git

        cd manifest-repo/backend
        sed -i "s|image: .*|image: $BACKEND_IMAGE:${{ github.sha }}|g" deployment.yaml

        cd ../frontend
        sed -i "s|image: .*|image: $FRONTEND_IMAGE:${{ github.sha }}|g" deployment.yaml

        cd ..

        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update images to ${{ github.sha }}" || echo "No changes to commit"
        git push origin main